configVersion: "1.0"

iotHub:
  authenticationMethod: symmetric_key

## IoT Edge configuration template to use
edgeConfiguration:
  # Will use default device_config
  # templateConfigPath: "./templates/purdue/device_config.toml"
  defaultEdgeAgent: "$upstream:443/azureiotedge-agent:1.2"

## Hierarchy of IoT Edge devices to create
edgeDevices:
  - deviceId: pi_1
    hostname: "10.120.60.53"
    edgeAgent: "mcr.microsoft.com/azureiotedge-agent:1.2"
    deployment: deployment-top.json
    children:
      - deviceId: pi_2
        hostname: "10.120.60.51"
        deployment: deployment-mid.json
        children:
          - deviceId: pi_3
            hostname: "10.120.60.61"
            deployment: deployment-low.json
